// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: city.sql

package validator

import (
	"context"
)

const getCities = `-- name: GetCities :many
SELECT label FROM cities ORDER BY population DESC, label
`

func (q *Queries) GetCities(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getCities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
