// Code generated by MockGen. DO NOT EDIT.
// Source: internal/quiz/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/quiz/service.go -destination=internal/quiz/mock_test.go -package=quiz
//

// Package quiz is a generated GoMock package.
package quiz

import (
	context "context"
	types "lowkeymycity/pkg/types"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockQuizService is a mock of QuizService interface.
type MockQuizService struct {
	ctrl     *gomock.Controller
	recorder *MockQuizServiceMockRecorder
	isgomock struct{}
}

// MockQuizServiceMockRecorder is the mock recorder for MockQuizService.
type MockQuizServiceMockRecorder struct {
	mock *MockQuizService
}

// NewMockQuizService creates a new mock instance.
func NewMockQuizService(ctrl *gomock.Controller) *MockQuizService {
	mock := &MockQuizService{ctrl: ctrl}
	mock.recorder = &MockQuizServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuizService) EXPECT() *MockQuizServiceMockRecorder {
	return m.recorder
}

// GetPersonalizedQuestions mocks base method.
func (m *MockQuizService) GetPersonalizedQuestions(ctx context.Context, city string) ([]Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPersonalizedQuestions", ctx, city)
	ret0, _ := ret[0].([]Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPersonalizedQuestions indicates an expected call of GetPersonalizedQuestions.
func (mr *MockQuizServiceMockRecorder) GetPersonalizedQuestions(ctx, city any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPersonalizedQuestions", reflect.TypeOf((*MockQuizService)(nil).GetPersonalizedQuestions), ctx, city)
}

// GetPreStoredQuestions mocks base method.
func (m *MockQuizService) GetPreStoredQuestions(ctx context.Context) ([]Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPreStoredQuestions", ctx)
	ret0, _ := ret[0].([]Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPreStoredQuestions indicates an expected call of GetPreStoredQuestions.
func (mr *MockQuizServiceMockRecorder) GetPreStoredQuestions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreStoredQuestions", reflect.TypeOf((*MockQuizService)(nil).GetPreStoredQuestions), ctx)
}

// GetResults mocks base method.
func (m *MockQuizService) GetResults(ctx context.Context, mode, city string, answers []Answer) (types.QuizResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResults", ctx, mode, city, answers)
	ret0, _ := ret[0].(types.QuizResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResults indicates an expected call of GetResults.
func (mr *MockQuizServiceMockRecorder) GetResults(ctx, mode, city, answers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResults", reflect.TypeOf((*MockQuizService)(nil).GetResults), ctx, mode, city, answers)
}

// MockSqlExecutor is a mock of SqlExecutor interface.
type MockSqlExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockSqlExecutorMockRecorder
	isgomock struct{}
}

// MockSqlExecutorMockRecorder is the mock recorder for MockSqlExecutor.
type MockSqlExecutorMockRecorder struct {
	mock *MockSqlExecutor
}

// NewMockSqlExecutor creates a new mock instance.
func NewMockSqlExecutor(ctrl *gomock.Controller) *MockSqlExecutor {
	mock := &MockSqlExecutor{ctrl: ctrl}
	mock.recorder = &MockSqlExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSqlExecutor) EXPECT() *MockSqlExecutorMockRecorder {
	return m.recorder
}

// AddCityQuestion mocks base method.
func (m *MockSqlExecutor) AddCityQuestion(ctx context.Context, arg AddCityQuestionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCityQuestion", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCityQuestion indicates an expected call of AddCityQuestion.
func (mr *MockSqlExecutorMockRecorder) AddCityQuestion(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCityQuestion", reflect.TypeOf((*MockSqlExecutor)(nil).AddCityQuestion), ctx, arg)
}

// GetCityQuestions mocks base method.
func (m *MockSqlExecutor) GetCityQuestions(ctx context.Context, cityLabel string) ([]GetCityQuestionsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCityQuestions", ctx, cityLabel)
	ret0, _ := ret[0].([]GetCityQuestionsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCityQuestions indicates an expected call of GetCityQuestions.
func (mr *MockSqlExecutorMockRecorder) GetCityQuestions(ctx, cityLabel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCityQuestions", reflect.TypeOf((*MockSqlExecutor)(nil).GetCityQuestions), ctx, cityLabel)
}

// GetMatchQuestions mocks base method.
func (m *MockSqlExecutor) GetMatchQuestions(ctx context.Context) ([]GetMatchQuestionsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMatchQuestions", ctx)
	ret0, _ := ret[0].([]GetMatchQuestionsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMatchQuestions indicates an expected call of GetMatchQuestions.
func (mr *MockSqlExecutorMockRecorder) GetMatchQuestions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMatchQuestions", reflect.TypeOf((*MockSqlExecutor)(nil).GetMatchQuestions), ctx)
}

// GetResultByCombination mocks base method.
func (m *MockSqlExecutor) GetResultByCombination(ctx context.Context, combination string) (Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResultByCombination", ctx, combination)
	ret0, _ := ret[0].(Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResultByCombination indicates an expected call of GetResultByCombination.
func (mr *MockSqlExecutorMockRecorder) GetResultByCombination(ctx, combination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResultByCombination", reflect.TypeOf((*MockSqlExecutor)(nil).GetResultByCombination), ctx, combination)
}

// SaveResult mocks base method.
func (m *MockSqlExecutor) SaveResult(ctx context.Context, arg SaveResultParams) (Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveResult", ctx, arg)
	ret0, _ := ret[0].(Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveResult indicates an expected call of SaveResult.
func (mr *MockSqlExecutorMockRecorder) SaveResult(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveResult", reflect.TypeOf((*MockSqlExecutor)(nil).SaveResult), ctx, arg)
}
