// Code generated by MockGen. DO NOT EDIT.
// Source: lowkeymycity/pkg/validator (interfaces: CityValidator)
//
// Generated by this command:
//
//	mockgen -destination=internal/quiz/mock_validator_test.go -package=quiz lowkeymycity/pkg/validator CityValidator
//

// Package quiz is a generated GoMock package.
package quiz

import (
	context "context"
	validator "lowkeymycity/pkg/validator"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCityValidator is a mock of CityValidator interface.
type MockCityValidator struct {
	ctrl     *gomock.Controller
	recorder *MockCityValidatorMockRecorder
	isgomock struct{}
}

// MockCityValidatorMockRecorder is the mock recorder for MockCityValidator.
type MockCityValidatorMockRecorder struct {
	mock *MockCityValidator
}

// NewMockCityValidator creates a new mock instance.
func NewMockCityValidator(ctrl *gomock.Controller) *MockCityValidator {
	mock := &MockCityValidator{ctrl: ctrl}
	mock.recorder = &MockCityValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCityValidator) EXPECT() *MockCityValidatorMockRecorder {
	return m.recorder
}

// Export mocks base method.
func (m *MockCityValidator) Export(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Export", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Export indicates an expected call of Export.
func (mr *MockCityValidatorMockRecorder) Export(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Export", reflect.TypeOf((*MockCityValidator)(nil).Export), path)
}

// GetCityID mocks base method.
func (m *MockCityValidator) GetCityID(city string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCityID", city)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetCityID indicates an expected call of GetCityID.
func (mr *MockCityValidatorMockRecorder) GetCityID(city any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCityID", reflect.TypeOf((*MockCityValidator)(nil).GetCityID), city)
}

// Init mocks base method.
func (m *MockCityValidator) Init(ctx context.Context, sql validator.SqlExecutor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", ctx, sql)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockCityValidatorMockRecorder) Init(ctx, sql any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockCityValidator)(nil).Init), ctx, sql)
}

// IsValid mocks base method.
func (m *MockCityValidator) IsValid(city string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValid", city)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsValid indicates an expected call of IsValid.
func (mr *MockCityValidatorMockRecorder) IsValid(city any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValid", reflect.TypeOf((*MockCityValidator)(nil).IsValid), city)
}
