// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package quiz

import (
	"github.com/jackc/pgx/v5/pgtype"
	"lowkeymycity/pkg/types"
)

type City struct {
	Label      string
	Population int32
}

type CityQuestion struct {
	CityLabel string
	Position  int32
	MeaningID string
	Text      string
	Options   []types.Option
}

type MatchQuestion struct {
	MeaningID string
	Position  int32
	Text      string
	Options   []types.Option
}

type Result struct {
	ID           string
	Combination  string
	Mode         string
	City         string
	Score        int32
	Title        string
	Summary      string
	GreenFlags   []string
	RedFlags     []string
	Alternatives []types.Alternative
	Closing      string
	CreatedAt    pgtype.Timestamptz
}
