// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quiz.sql

package quiz

import (
	"context"

	"lowkeymycity/pkg/types"
)

const addCityQuestion = `-- name: AddCityQuestion :exec
INSERT INTO city_questions (city_label, position, meaning_id, text, options)
VALUES ($1, $2, $3, $4, $5)
`

type AddCityQuestionParams struct {
	CityLabel string
	Position  int32
	MeaningID string
	Text      string
	Options   []types.Option
}

func (q *Queries) AddCityQuestion(ctx context.Context, arg AddCityQuestionParams) error {
	_, err := q.db.Exec(ctx, addCityQuestion,
		arg.CityLabel,
		arg.Position,
		arg.MeaningID,
		arg.Text,
		arg.Options,
	)
	return err
}

const getCityQuestions = `-- name: GetCityQuestions :many
SELECT meaning_id, text, options FROM city_questions
WHERE city_label = $1
ORDER BY position
`

type GetCityQuestionsRow struct {
	MeaningID string
	Text      string
	Options   []types.Option
}

func (q *Queries) GetCityQuestions(ctx context.Context, cityLabel string) ([]GetCityQuestionsRow, error) {
	rows, err := q.db.Query(ctx, getCityQuestions, cityLabel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCityQuestionsRow
	for rows.Next() {
		var i GetCityQuestionsRow
		if err := rows.Scan(&i.MeaningID, &i.Text, &i.Options); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatchQuestions = `-- name: GetMatchQuestions :many
SELECT meaning_id, text, options FROM match_questions
ORDER BY position
`

type GetMatchQuestionsRow struct {
	MeaningID string
	Text      string
	Options   []types.Option
}

func (q *Queries) GetMatchQuestions(ctx context.Context) ([]GetMatchQuestionsRow, error) {
	rows, err := q.db.Query(ctx, getMatchQuestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMatchQuestionsRow
	for rows.Next() {
		var i GetMatchQuestionsRow
		if err := rows.Scan(&i.MeaningID, &i.Text, &i.Options); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResultByCombination = `-- name: GetResultByCombination :one
SELECT id, combination, mode, city, score, title, summary, green_flags, red_flags, alternatives, closing, created_at FROM results
WHERE combination = $1
`

func (q *Queries) GetResultByCombination(ctx context.Context, combination string) (Result, error) {
	row := q.db.QueryRow(ctx, getResultByCombination, combination)
	var i Result
	err := row.Scan(
		&i.ID,
		&i.Combination,
		&i.Mode,
		&i.City,
		&i.Score,
		&i.Title,
		&i.Summary,
		&i.GreenFlags,
		&i.RedFlags,
		&i.Alternatives,
		&i.Closing,
		&i.CreatedAt,
	)
	return i, err
}

const saveResult = `-- name: SaveResult :one
INSERT INTO results (combination, mode, city, score, title, summary,
                     green_flags, red_flags, alternatives, closing)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (combination) DO UPDATE SET combination = EXCLUDED.combination
RETURNING id, combination, mode, city, score, title, summary, green_flags, red_flags, alternatives, closing, created_at
`

type SaveResultParams struct {
	Combination  string
	Mode         string
	City         string
	Score        int32
	Title        string
	Summary      string
	GreenFlags   []string
	RedFlags     []string
	Alternatives []types.Alternative
	Closing      string
}

// the no-op update makes RETURNING yield the existing row when two
// identical submissions race, instead of failing the second one
func (q *Queries) SaveResult(ctx context.Context, arg SaveResultParams) (Result, error) {
	row := q.db.QueryRow(ctx, saveResult,
		arg.Combination,
		arg.Mode,
		arg.City,
		arg.Score,
		arg.Title,
		arg.Summary,
		arg.GreenFlags,
		arg.RedFlags,
		arg.Alternatives,
		arg.Closing,
	)
	var i Result
	err := row.Scan(
		&i.ID,
		&i.Combination,
		&i.Mode,
		&i.City,
		&i.Score,
		&i.Title,
		&i.Summary,
		&i.GreenFlags,
		&i.RedFlags,
		&i.Alternatives,
		&i.Closing,
		&i.CreatedAt,
	)
	return i, err
}
